### ISSUE TITLE
Ruby gems should get reused rather than rebuilt

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/bundle-install#12]
**When** I am pack building a ruby app that has a Gemfile
**I Want** my gems to be reused when possible
**So That** my app is built faster

**Given**
I am building a ruby app that has a Gemfile
**When**
The gems can be reused and pulled rather than re-built
**Then**
The gems are reused and I am informed that the gems were reused

**Comment by drnic** [comment]
New rails 6 app takes 4.5m to `bundle install` each time. Caching FTW.

```
[builder] Bundle Install Buildpack 0.0.11
[builder]   Executing build process
[builder]     Running 'bundle install'
[builder]       Completed in 4m23.042s
```

**Comment by kvedurmu** [comment]
Looks like we'll also need to implement https://github.com/paketo-community/bundle-install/issues/4 in order to support this.
